# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
distanceMatrixTest <- function(filePath) {
    .Call('_DynamicOrienteeringAlgorithms_distanceMatrixTest', PACKAGE = 'DynamicOrienteeringAlgorithms', filePath)
}

#' @export
exportToDistanceMatrix <- function(nodeDf, arcDf, problemDf, problemName, destination) {
    invisible(.Call('_DynamicOrienteeringAlgorithms_exportToDistanceMatrix', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, problemName, destination))
}

#' @export
readDistanceMatrix <- function(pathToMatrix) {
    .Call('_DynamicOrienteeringAlgorithms_readDistanceMatrix', PACKAGE = 'DynamicOrienteeringAlgorithms', pathToMatrix)
}

#' @export
callEa4OpSolver <- function(nodeDf, arcDf, problemDf, budget, problemName, runNumber = 0L, fileSuffix = "", pathToChanges = "", pathToDistanceMatrix = "") {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callEa4OpSolver', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, problemName, runNumber, fileSuffix, pathToChanges, pathToDistanceMatrix))
}

#' @export
callEa4OpImprover <- function(nodeDf, arcDf, problemDf, budget, problemName, runNumber, pathToInitialSolution, dominanceOfInitialSolution = 0.5, fileSuffix = "", pathToChanges = "", pathToDistanceMatrix = "") {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callEa4OpImprover', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, problemName, runNumber, pathToInitialSolution, dominanceOfInitialSolution, fileSuffix, pathToChanges, pathToDistanceMatrix))
}

#' @export
callEvaluator <- function(nodeDf, arcDf, problemDf, budget, indices, pathToDistanceMatrix = "") {
    .Call('_DynamicOrienteeringAlgorithms_callEvaluator', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, indices, pathToDistanceMatrix)
}

#' @export
callGraspSrSolver <- function(nodeDf, arcDf, problemDf, budget, problemName, runNumber = 0L, fileSuffix = "", pathToChanges = "", pathToDistanceMatrix = "") {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callGraspSrSolver', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, problemName, runNumber, fileSuffix, pathToChanges, pathToDistanceMatrix))
}

#' @export
callGraspSrImprover <- function(nodeDf, arcDf, problemDf, budget, problemName, runNumber, pathToInitialSolution, fileSuffix = "", pathToChanges = "", pathToDistanceMatrix = "") {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callGraspSrImprover', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, problemName, runNumber, pathToInitialSolution, fileSuffix, pathToChanges, pathToDistanceMatrix))
}

#' @export
convertLGFtoR <- function(filePath) {
    .Call('_DynamicOrienteeringAlgorithms_convertLGFtoR', PACKAGE = 'DynamicOrienteeringAlgorithms', filePath)
}

#' @export
saveDigraphAsLGF <- function(filePath, nodeDf, arcDf) {
    invisible(.Call('_DynamicOrienteeringAlgorithms_saveDigraphAsLGF', PACKAGE = 'DynamicOrienteeringAlgorithms', filePath, nodeDf, arcDf))
}

#' @export
saveDigraphWithProblemDataAsLGF <- function(filePath, nodeDf, arcDf, problemDf, budget) {
    invisible(.Call('_DynamicOrienteeringAlgorithms_saveDigraphWithProblemDataAsLGF', PACKAGE = 'DynamicOrienteeringAlgorithms', filePath, nodeDf, arcDf, problemDf, budget))
}

#' @export
naiveInitialSolution <- function(nodeDf, arcDf, problemDf, budget, problemName = "", fileSuffix = "", pathToDistanceMatrix = "") {
    invisible(.Call('_DynamicOrienteeringAlgorithms_naiveInitialSolution', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, problemName, fileSuffix, pathToDistanceMatrix))
}

#' @export
plotNetworkRoute_R <- function(nodeDf, arcDf, problemDf, nodeIDs) {
    invisible(.Call('_DynamicOrienteeringAlgorithms_plotNetworkRoute_R', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, nodeIDs))
}

#' @export
callRandomSolver <- function(nodeDf, arcDf, problemDf, budget, algoName = "random", problemName = "", fileSuffix = "", pathToDistanceMatrix = "") {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callRandomSolver', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, algoName, problemName, fileSuffix, pathToDistanceMatrix))
}

#' @export
callRandomImprover <- function(nodeDf, arcDf, problemDf, budget, algoName = "random", problemName = "", pathToInitialSolution = "", fileSuffix = "", pathToDistanceMatrix = "") {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callRandomImprover', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, algoName, problemName, pathToInitialSolution, fileSuffix, pathToDistanceMatrix))
}

#' @export
callVNSSolver <- function(nodeDf, arcDf, problemDf, budget, problemName, runNumber, fileSuffix = "", pathToChanges = "", pathToDistanceMatrix = "", withLocalSearch = FALSE, withLinKernighan = TRUE, perturbationProbability = 0.15) {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callVNSSolver', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, problemName, runNumber, fileSuffix, pathToChanges, pathToDistanceMatrix, withLocalSearch, withLinKernighan, perturbationProbability))
}

#' @export
callVNSImprover <- function(nodeDf, arcDf, problemDf, budget, problemName, runNumber, pathToInitialSolution, fileSuffix = "", pathToChanges = "", pathToDistanceMatrix = "", withLocalSearch = FALSE, withLinKernighan = TRUE, perturbationProbability = 0.15) {
    invisible(.Call('_DynamicOrienteeringAlgorithms_callVNSImprover', PACKAGE = 'DynamicOrienteeringAlgorithms', nodeDf, arcDf, problemDf, budget, problemName, runNumber, pathToInitialSolution, fileSuffix, pathToChanges, pathToDistanceMatrix, withLocalSearch, withLinKernighan, perturbationProbability))
}

